### ISSUE TITLE
FR - Adding --output-format flag for raw(cbor) metadata output and --nonce flag

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/voting-tools#20]
Feature-Request:

Adding a `--output-format` flag with the values: **txbody**, **txsigned** and **metadata**
Adding a `--nonce` flag to provide custom data instead of fixed value slotHeight

In `--output-format metadata` mode this would reduce the needed input-flags to:
``` console
./voter-registration --payment-address STRING 
                     --vote-public-key FILE 
                     --stake-signing-key FILE 
                     --nonce NONCE 
                     (--mainnet | --testnet-magic NATURAL) 
                     --output-format metadata 
                     --out-file FILE
```

The metadata out-file format should be _binary(cbor)_ format so it can be attached to a transaction via the `cardano-cli transaction build-raw --metadata-cbor-file` flag.

This would also be in line with the `cardano-hw-cli` workflow for voting with hw-wallets, which also generates the metadata-cbor-file in raw(binary) format.

P.S.: Maybe it would also be an idea to rename the `--payment-address` flag into `--rewards-payout-address` flag, because maybe --payment-address is misleading here. The transaction including such a voting-registration-metadata can be paid by any wallet.

Tag: @disassembler

**Comment by gitmachtl** [comment]
The ability to just generate the `voting-registration-metadata.cbor` file would automatically introduce the ability to do it offline too.

**Comment by gitmachtl** [comment]
Recent changed in the Rewards-Payout should be reflected in changing the `--payment-address STRING` parameter into `--rewards-address STRING` like:

```console
./voter-registration --vote-public-key FILE 
                     --stake-signing-key FILE 
                     --reward-address STRING
                     --nonce NONCE 
                     (--mainnet | --testnet-magic NATURAL) 
                     --output-format metadata 
                     --out-file FILE
```

**Comment by sevanspowell** [comment]
@gitmachtl I can't give you a timeline, but we will be working on this :+1:

**Comment by sevanspowell** [comment]
Addressed in https://github.com/input-output-hk/voting-tools/pull/28
