### ISSUE TITLE
voter-registration tool not working anymore in alonzo-era

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/voting-tools#26]
The Voter-Registration tool is no longer working with node 1.30.1 and later in the Alonzo-Era. Trying to generate a Catalyst Registration Tx results in the following error message:

``` console
$ ./voter-registration --payment-signing-key somepay.skey  --payment-address $(cat somepay.addr) --rewards-address $(cat voting/catalyst-rewards.staking.addr) --vote-public-key voting/vote.pkey --stake-signing-key pledge.staking.skey --cardano-mode --mainnet --out-file voting/catalystregistration.tx

voter-registration: DecoderFailure (LocalStateQuery HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))) Query (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) ServerAgency TokQuerying QueryIfCurrent (QS (QZ GetCurrentPParams))) (DeserialiseFailure 15 "decodeNS: invalid index 4")
```

The Catalyst Toolbox Repo (https://github.com/input-output-hk/catalyst-toolbox) do not include a registration signing feature yet, soo....   are we now stuck here?

**Comment by gitmachtl** [comment]
I think we should retire this repo and shift it to the catalyst-toolbox. I also submitted an issue there: https://github.com/input-output-hk/catalyst-toolbox/issues/73

**Comment by gitmachtl** [comment]
Whats the current dev status here? Catalyst voting registration will end in 1 month.

**Comment by sevanspowell** [comment]
Fixed in https://github.com/input-output-hk/voting-tools/pull/27
